// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFCAr8KUEB9X_05m5iSr-n9wZabVbbdM',
    appId: '1:196454276642:android:c3038bebdbeef6ad9f747b',
    messagingSenderId: '196454276642',
    projectId: 'little-vegan-eats-app-e1cd3',
    storageBucket: 'little-vegan-eats-app-e1cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNaJxG9Sy19Q_4zeaseYRSYTrmi9ODRc8',
    appId: '1:196454276642:ios:6bf85c9f429edc919f747b',
    messagingSenderId: '196454276642',
    projectId: 'little-vegan-eats-app-e1cd3',
    storageBucket: 'little-vegan-eats-app-e1cd3.firebasestorage.app',
    iosClientId: '196454276642-3u9f9p7m9mav4252llan8ce32hj28jn5.apps.googleusercontent.com',
    iosBundleId: 'co.littleveganeats.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNaJxG9Sy19Q_4zeaseYRSYTrmi9ODRc8',
    appId: '1:196454276642:ios:7634bbd7b41b8b569f747b',
    messagingSenderId: '196454276642',
    projectId: 'little-vegan-eats-app-e1cd3',
    storageBucket: 'little-vegan-eats-app-e1cd3.firebasestorage.app',
    iosClientId: '196454276642-hg8vii5peam0c6dqcge0hud2f5ahg5o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.littleVeganEats',
  );

}